In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

In [2]:
df = pd.read_csv("Iris.csv")


In [3]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
labels = df["Species"]

In [5]:
labels

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [6]:
# Lets do one hot encoding on species column
df_encoded = pd.get_dummies(data=labels).astype(int)

In [7]:
# These are the target values
df_encoded

Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]

In [8]:
# Lets change the from df_encoded to labels for easy understading
labels = df_encoded.values
labels

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [9]:
df.head()


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [10]:
features = df.drop("Species", axis=1).values

In [11]:
# Now we have both the feature and the labels both in different datasets
features

array([[1.00e+00, 5.10e+00, 3.50e+00, 1.40e+00, 2.00e-01],
       [2.00e+00, 4.90e+00, 3.00e+00, 1.40e+00, 2.00e-01],
       [3.00e+00, 4.70e+00, 3.20e+00, 1.30e+00, 2.00e-01],
       [4.00e+00, 4.60e+00, 3.10e+00, 1.50e+00, 2.00e-01],
       [5.00e+00, 5.00e+00, 3.60e+00, 1.40e+00, 2.00e-01],
       [6.00e+00, 5.40e+00, 3.90e+00, 1.70e+00, 4.00e-01],
       [7.00e+00, 4.60e+00, 3.40e+00, 1.40e+00, 3.00e-01],
       [8.00e+00, 5.00e+00, 3.40e+00, 1.50e+00, 2.00e-01],
       [9.00e+00, 4.40e+00, 2.90e+00, 1.40e+00, 2.00e-01],
       [1.00e+01, 4.90e+00, 3.10e+00, 1.50e+00, 1.00e-01],
       [1.10e+01, 5.40e+00, 3.70e+00, 1.50e+00, 2.00e-01],
       [1.20e+01, 4.80e+00, 3.40e+00, 1.60e+00, 2.00e-01],
       [1.30e+01, 4.80e+00, 3.00e+00, 1.40e+00, 1.00e-01],
       [1.40e+01, 4.30e+00, 3.00e+00, 1.10e+00, 1.00e-01],
       [1.50e+01, 5.80e+00, 4.00e+00, 1.20e+00, 2.00e-01],
       [1.60e+01, 5.70e+00, 4.40e+00, 1.50e+00, 4.00e-01],
       [1.70e+01, 5.40e+00, 3.90e+00, 1.30e+00, 4.00e-01

In [12]:
# Now lets perform lets split the data into training and testing
from sklearn.model_selection import train_test_split

This is the classical way of splitting data into training and tesing

In [13]:
X_train, X_test,y_train, y_test = train_test_split(features,labels,test_size=0.2,random_state=33)

In [14]:
# As we can see these are numpy arrays so we have to change it into tensor after that we can use it in neural network
X_train

array([[9.50e+01, 5.60e+00, 2.70e+00, 4.20e+00, 1.30e+00],
       [8.70e+01, 6.70e+00, 3.10e+00, 4.70e+00, 1.50e+00],
       [1.22e+02, 5.60e+00, 2.80e+00, 4.90e+00, 2.00e+00],
       [1.16e+02, 6.40e+00, 3.20e+00, 5.30e+00, 2.30e+00],
       [1.41e+02, 6.70e+00, 3.10e+00, 5.60e+00, 2.40e+00],
       [1.46e+02, 6.70e+00, 3.00e+00, 5.20e+00, 2.30e+00],
       [1.02e+02, 5.80e+00, 2.70e+00, 5.10e+00, 1.90e+00],
       [9.60e+01, 5.70e+00, 3.00e+00, 4.20e+00, 1.20e+00],
       [9.40e+01, 5.00e+00, 2.30e+00, 3.30e+00, 1.00e+00],
       [3.50e+01, 4.90e+00, 3.10e+00, 1.50e+00, 1.00e-01],
       [8.80e+01, 6.30e+00, 2.30e+00, 4.40e+00, 1.30e+00],
       [9.30e+01, 5.80e+00, 2.60e+00, 4.00e+00, 1.20e+00],
       [9.80e+01, 6.20e+00, 2.90e+00, 4.30e+00, 1.30e+00],
       [3.00e+00, 4.70e+00, 3.20e+00, 1.30e+00, 2.00e-01],
       [7.00e+00, 4.60e+00, 3.40e+00, 1.40e+00, 3.00e-01],
       [9.90e+01, 5.10e+00, 2.50e+00, 3.00e+00, 1.10e+00],
       [1.20e+01, 4.80e+00, 3.40e+00, 1.60e+00, 2.00e-01

In [15]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)


In [16]:
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)
y_train

tensor([[0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],

In [17]:
# Now let's try the torch method is which is a little more convenient
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [21]:
# We will be using the same dataset
labels = pd.get_dummies(data= df["Species"]).astype(int).values

In [22]:
labels

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [24]:
data = df.drop("Species", axis=1).values

In [25]:
data

array([[1.00e+00, 5.10e+00, 3.50e+00, 1.40e+00, 2.00e-01],
       [2.00e+00, 4.90e+00, 3.00e+00, 1.40e+00, 2.00e-01],
       [3.00e+00, 4.70e+00, 3.20e+00, 1.30e+00, 2.00e-01],
       [4.00e+00, 4.60e+00, 3.10e+00, 1.50e+00, 2.00e-01],
       [5.00e+00, 5.00e+00, 3.60e+00, 1.40e+00, 2.00e-01],
       [6.00e+00, 5.40e+00, 3.90e+00, 1.70e+00, 4.00e-01],
       [7.00e+00, 4.60e+00, 3.40e+00, 1.40e+00, 3.00e-01],
       [8.00e+00, 5.00e+00, 3.40e+00, 1.50e+00, 2.00e-01],
       [9.00e+00, 4.40e+00, 2.90e+00, 1.40e+00, 2.00e-01],
       [1.00e+01, 4.90e+00, 3.10e+00, 1.50e+00, 1.00e-01],
       [1.10e+01, 5.40e+00, 3.70e+00, 1.50e+00, 2.00e-01],
       [1.20e+01, 4.80e+00, 3.40e+00, 1.60e+00, 2.00e-01],
       [1.30e+01, 4.80e+00, 3.00e+00, 1.40e+00, 1.00e-01],
       [1.40e+01, 4.30e+00, 3.00e+00, 1.10e+00, 1.00e-01],
       [1.50e+01, 5.80e+00, 4.00e+00, 1.20e+00, 2.00e-01],
       [1.60e+01, 5.70e+00, 4.40e+00, 1.50e+00, 4.00e-01],
       [1.70e+01, 5.40e+00, 3.90e+00, 1.30e+00, 4.00e-01

In [34]:
from torch.utils.data import TensorDataset , DataLoader

In [35]:
iris = TensorDataset(torch.FloatTensor(data), torch.LongTensor(labels))

In [36]:
type(iris)

torch.utils.data.dataset.TensorDataset

In [37]:
iris

In [38]:
for i in iris:
    print (i)

(tensor([1.0000, 5.1000, 3.5000, 1.4000, 0.2000]), tensor([1, 0, 0]))
(tensor([2.0000, 4.9000, 3.0000, 1.4000, 0.2000]), tensor([1, 0, 0]))
(tensor([3.0000, 4.7000, 3.2000, 1.3000, 0.2000]), tensor([1, 0, 0]))
(tensor([4.0000, 4.6000, 3.1000, 1.5000, 0.2000]), tensor([1, 0, 0]))
(tensor([5.0000, 5.0000, 3.6000, 1.4000, 0.2000]), tensor([1, 0, 0]))
(tensor([6.0000, 5.4000, 3.9000, 1.7000, 0.4000]), tensor([1, 0, 0]))
(tensor([7.0000, 4.6000, 3.4000, 1.4000, 0.3000]), tensor([1, 0, 0]))
(tensor([8.0000, 5.0000, 3.4000, 1.5000, 0.2000]), tensor([1, 0, 0]))
(tensor([9.0000, 4.4000, 2.9000, 1.4000, 0.2000]), tensor([1, 0, 0]))
(tensor([10.0000,  4.9000,  3.1000,  1.5000,  0.1000]), tensor([1, 0, 0]))
(tensor([11.0000,  5.4000,  3.7000,  1.5000,  0.2000]), tensor([1, 0, 0]))
(tensor([12.0000,  4.8000,  3.4000,  1.6000,  0.2000]), tensor([1, 0, 0]))
(tensor([13.0000,  4.8000,  3.0000,  1.4000,  0.1000]), tensor([1, 0, 0]))
(tensor([14.0000,  4.3000,  3.0000,  1.1000,  0.1000]), tensor([1, 0, 

As we can easily the dataset is divided in data and labels

In [39]:
len(iris)

150

Now we will work on batches.
Batches are used when we have a very large datasets and we have 100s or 1000s of rows and columns so we shuffle our data and devide it into batches.
1 epoch is complete when all batches are completed.

In [43]:
iris_loader = DataLoader(iris, batch_size = 10, shuffle = True)


In [44]:
for batch in iris_loader:
    print(batch)

[tensor([[111.0000,   6.5000,   3.2000,   5.1000,   2.0000],
        [ 98.0000,   6.2000,   2.9000,   4.3000,   1.3000],
        [ 42.0000,   4.5000,   2.3000,   1.3000,   0.3000],
        [104.0000,   6.3000,   2.9000,   5.6000,   1.8000],
        [107.0000,   4.9000,   2.5000,   4.5000,   1.7000],
        [  8.0000,   5.0000,   3.4000,   1.5000,   0.2000],
        [ 40.0000,   5.1000,   3.4000,   1.5000,   0.2000],
        [150.0000,   5.9000,   3.0000,   5.1000,   1.8000],
        [ 80.0000,   5.7000,   2.6000,   3.5000,   1.0000],
        [ 52.0000,   6.4000,   3.2000,   4.5000,   1.5000]]), tensor([[0, 0, 1],
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 1],
        [0, 0, 1],
        [1, 0, 0],
        [1, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0]])]
[tensor([[5.5000e+01, 6.5000e+00, 2.8000e+00, 4.6000e+00, 1.5000e+00],
        [1.2600e+02, 7.2000e+00, 3.2000e+00, 6.0000e+00, 1.8000e+00],
        [1.0000e+02, 5.7000e+00, 2.8000e+00, 4.1000e+00, 1.3000e