A torch is generalized form of matrix

In [1]:
import numpy as np
import torch


In [2]:

arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr.dtype

dtype('int32')

In [5]:
type(arr)

numpy.ndarray

In [6]:
# Converting array to torch
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [7]:
arr2 = np.arange(1,10).reshape(3,3)

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Coverting a 2d array to torch
torch = torch.from_numpy(arr2)

In [10]:
torch

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

In [11]:
type(torch)

torch.Tensor

In [12]:
arr3 = np.arange(1,17).reshape(4,4)
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
#  Another way to convert it to tensor
arr4 = np.arange(1,21).reshape(5,4)
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [21]:
torch4 = torch.as_tensor(arr4)
torch4

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]], dtype=torch.int32)

In [22]:
type(torch4)

torch.Tensor

In [23]:
arr4[0,0] = 99999
arr4

array([[99999,     2,     3,     4],
       [    5,     6,     7,     8],
       [    9,    10,    11,    12],
       [   13,    14,    15,    16],
       [   17,    18,    19,    20]])

In [24]:
torch4

tensor([[99999,     2,     3,     4],
        [    5,     6,     7,     8],
        [    9,    10,    11,    12],
        [   13,    14,    15,    16],
        [   17,    18,    19,    20]], dtype=torch.int32)

As we can see from the above that making changes in array also making changes in torch tensor so now we will make a copy of an array so that making changes in one array dosent effect the other.

In [27]:
array = np.arange(1,26).reshape(5,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
my_torch = torch.Tensor(array)
my_torch

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25.]])

Note : If use torch.Tensor using capital 'T' then the output will be in float, Using lower case 't' torch.tensor will give the output as it was in array

In [30]:
array[0,0] = 99999
array

array([[99999,     2,     3,     4,     5],
       [    6,     7,     8,     9,    10],
       [   11,    12,    13,    14,    15],
       [   16,    17,    18,    19,    20],
       [   21,    22,    23,    24,    25]])

In [31]:
my_torch

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25.]])

We can see from the above that changes in one array dosen't affect the torch by using torch.tensor

Most of the tensor functions are like numpy and also have same syntax