In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[8]

8

In [5]:
arr[3]

3

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[5:10]

array([5, 6, 7, 8, 9])

In [8]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr_2 = arr[1:5]

In [10]:
arr_2

array([1, 2, 3, 4])

In [11]:
arr_2 * 5

array([ 5, 10, 15, 20])

In [12]:
arr_2

array([1, 2, 3, 4])

In [13]:
new_arr = arr_2[:] * 5

In [14]:
new_arr 

array([ 5, 10, 15, 20])

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
slice_of_arr = arr[1:6]

In [17]:
slice_of_arr

array([1, 2, 3, 4, 5])

In [18]:
slice_of_arr[:] = 99 

In [19]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [20]:
#we have made changes in slice_of_arr variable but we havent make a copy of arr so the changes made in slice_of_arr
# will also be made in arr
arr

array([ 0, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [25]:
#to make a copy of arr
slice_of_arr2 = arr.copy()

In [29]:
#now we have make a copy of arr so we can make changes into slice of array and it will not effect the orignal arr
slice_of_arr2[:] = 1000

In [30]:
slice_of_arr2

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [31]:
arr

array([ 0, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [37]:
#Now lets work on 2d arrays
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
#lets grab 5 in 2nd row and in 2nd column
arr_2d[1,1]

5

In [48]:
#lets create a sub matrix from the above matrix
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [49]:
#now lets work on conditions in numpy
arr

array([ 0, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [52]:
arr<99

array([ True, False, False, False, False, False,  True,  True,  True,
        True])

In [53]:
bool_arr = arr<99

In [54]:
bool_arr

array([ True, False, False, False, False, False,  True,  True,  True,
        True])

In [55]:
arr[bool_arr]


array([0, 6, 7, 8, 9])

In [57]:
#another simple way to do all the above code in just one line is
arr[arr<99]

array([0, 6, 7, 8, 9])