Introduction To NumPy

In [1]:
#First We are Going to import Numpy
import numpy as np

In [3]:
myList = [1,2,3]

In [4]:
type(myList)

list

In [6]:
#changing list to an array
np.array(myList)

array([1, 2, 3])

In [8]:
#As we can the type of the variable is still list
type(myList)

list

In [9]:
#to change it in array we have to store it in another variable
arr = np.array(myList)

In [10]:
type(arr)

numpy.ndarray

In [11]:
#Nested List
myList2 = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
myList2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
arr2 = np.array(myList2)

In [14]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#Some built-in method of numpy
arr2.shape

(3, 3)

In [16]:
#First digit is inclusive and last digit is exclusive
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#using to 2 in the end will have a 2 digits gape between numbers
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
#you can add a tuple to an array to have multi dimention array
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
#you can do mathematics operation directly to a numpy array
np.ones((3,5))*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [22]:
#Linspace is used to linearly seperate numbers
np.linspace(1,10,4)
#this will give 4 digits linearly spaced between 1 to 10

array([ 1.,  4.,  7., 10.])

In [24]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [32]:
#Now we will talk about Random Variable
np.random.rand(10)
#rand will print between 0 and 1

array([0.64547957, 0.26681212, 0.63393989, 0.67752691, 0.99949101,
       0.73878166, 0.61769232, 0.58123099, 0.46894743, 0.74161819])

In [33]:
np.random.randn(10)

array([ 0.13325302, -0.50411946,  0.85819699,  1.54186795,  0.57564425,
       -1.49007545, -0.06482411,  0.08900346,  0.02078474,  0.18163635])

In [42]:
#randint will print a random number
np.random.randint(10)

8

In [44]:
arr = np.arange(25)

In [47]:
#we have used the shape method now we will use the reshape method to reshape the array
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
#Note we will have to know how many elements we have into array before reshaping it
arr.reshape(5,3)
#we can't reshape 25 number into a 5 by 3 array

ValueError: cannot reshape array of size 25 into shape (5,3)